name: cconta_pub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Mi primer actions"
        run: echo "Ejecutando actions"
      - name:  "Mostarando variables por defecto"
        run: |
          echo "Evento: ${{toJSON(github.event)}}"}"
