name: cconta_pub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Mi primer actions"
        run: echo "Ejecutando actions"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{ toJSON(github.event) }}"
            # Verifica el código del repositorio
      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Usa la versión compatible con Expo

      # Instala las dependencias
      - name: Install dependencies
        run: npm ci

      # Ejecuta pruebas
      - name: Run tests
        run: npm run test
